


variables:
  TERM: "xterm"
  DISPLAY: ":99.0"
  PYVISTA_OFF_SCREEN: "true"


stages:
  - badge
  - zenodo
  - trigdoc
  # - trigdocker
  - test

.before-python: &before-python
  ## install os tools
  - apt-get update -q && apt-get install -q -y --no-install-recommends make libgl1-mesa-dev xvfb
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - sed -i 's/name protis/name base/g' environment.yml
  - conda install mamba
  - mamba env update -n base -f environment.yml
  # - conda env create -f environment.yml
  # - source activate protis
  - python -V  # Print out python version for debugging
  # pyvista config for x server
  # see https://github.com/pyvista/gl-ci-helpers/blob/master/travis/setup_headless_display.sh
  # - export DISPLAY=:99.0
  # - export PYVISTA_OFF_SCREEN=True
  - which Xvfb
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sleep 3



badge:
  stage: badge
  image:
    name: alpine/git:latest
    entrypoint: [""]
  script:
    - echo "collecting stats for badges"
    - commits=`git rev-list --all --count`
    - latest_release_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
    - logo=$(cat ./doc/_assets/opt.svg | tr '"' "'")
    - echo {\"schemaVersion\":"1", \"commits\":\"$commits\", \"release_tag\":\"$latest_release_tag\"} > badges.json
    - echo {\"schemaVersion\":"1", \"logoSvg\":\"$logo\", \"label\":\"release\", \"message\":\"$latest_release_tag\", \"color\":\"8c4ab0\", \"labelColor\":\"dedede\", \"style\":\"for-the-badge\"} > logobadge.json
  artifacts:
    paths:
        - badges.json
        - logobadge.json

staging:
  stage: trigdoc
  trigger: protis/protis.gitlab.io
  only:
    - main


test:
  stage: test
  image: continuumio/miniconda3:latest
  before_script:
    - *before-python
  script:
    - make install
    - make test-req
    - make test
    - coverage xml
  coverage: '/TOTAL.*\s([.\d]+)%/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  only:
    - main



send-snapshot:
  stage: zenodo
  image: python
  script:
    - if [[ ! $CI_COMMIT_TAG =~ ^v?[0-9]+\.[0-9]+ ]]; then exit 0; fi
    - pip install gitlab2zenodo
    - git archive --format zip --output ${CI_COMMIT_TAG#v}.zip ${CI_COMMIT_TAG}
    - g2z-send -p -m .zenodo.json ${CI_COMMIT_TAG#v}.zip
  only:
    - tags
