name: protis
channels:
  - conda-forge
  - pytorch
dependencies:
  - python>=3.8
  - pip
  - numpy
  - scipy
  - matplotlib-base
  - shapely
  - joblib
  - colorlog
  - psutil
  - ipython
  - nlopt
  - pytorch
  - magma
  - cudatoolkit=10.2
  - pyvista
  - pythreejs
  - ipyvtklink
  - panel
  - autograd
  - pip:
    - nannos>=2.5.0
    - git+https://gitlab.com/protis/protis.git
