name: protis
channels:
  - conda-forge
  - pytorch
dependencies:
  - python>=3.8
  - pip
  - numpy
  - scipy
  - matplotlib-base
  - shapely
  - joblib
  - colorlog
  - psutil
  - ipython
  - nlopt
  - pytorch
  - pytorch-gpu
  - jax
  - jaxlib
  - magma
  - pyvista
  - pythreejs
  - ipyvtklink
  - panel
  - autograd
  - scikit-image
  - pip:
    - nannos>=2.5.0
    - git+https://gitlab.com/protis/protis.git
